---
title: "pres"
author: "Heidi Rautiainen"
date: "2025-01-14"
output:
  html_document:
    df_print: paged
---

### maps for presentations

# WORLD MAPS

# Load packages

```{r echo = FALSE}

pcks <- list("dplyr", 
             "raster", # used for raster data
             "terra", # used for raster data 
             "sf", # used for handling sppatial data (e.g. setting coordinate ref system)
             "ggspatial", # for creating maps in ggplot 
             "tidyverse")

sapply(pcks, require, char = TRUE) 
library(rnaturalearth)
```

## SLIDE 1

```{r echo = FALSE}

world <- ne_countries(scale = 10) # country = c("Sweden")) # Check projection 
sf::st_crs(world)$proj4string # unprojected # 
world <- st_transform(world, 
                      crs ="+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

world1 <- st_transform(world, 
                       crs ="+proj=laea +x_0=0 + y_0=0 +lon_0=0 +lat_0=0") 
world2 <- st_transform(world, 
                       crs ="+proj=laea +x_0=0 + y_0=0 +lon_0=-74 +lat_0=40") 
plot(world2) 



ggplot() +

# plot the world 
  geom_sf(data = world1, aes(geometry = world1$geometry), fill= "antiquewhite")+

# add grid lines 
  theme(panel.grid.major = element_line(color = gray(.5), 
                                        linetype = "dashed", 
                                        linewidth = 0.1), 
        panel.background = element_rect(fill = "white"))

# ggsave("misc/worldmap1.png", width = 8, height = 6, dpi = 400)

# plot the world

ggplot() +

geom_sf(data = world2, aes(geometry = world2$geometry), fill= "antiquewhite")+

  # add grid lines 
  theme(panel.grid.major = element_line(color = gray(.5),
                                        linetype = "dashed",
                                        linewidth = 0.1),
        panel.background = element_rect(fill = "white"))

# ggsave("misc/worldmap2.png", width = 8, height = 6, dpi = 400)


```

### Make maps in R

```{r echo = FALSE}

library(sf) 
library(geodata) #roads 
library(rnaturalearth) # map of swe
library(ggplot2) 
library(dplyr)

swe <- ne_countries(country="sweden", scale = 10) %>%   # get data
  st_as_sf(.) %>%                                       # as sf object 
  st_crop(., xmin = 17.55, xmax= 17.79,                 # bbox
          ymin=59.9, ymax=59.8)

roads <- geodata::osm(country="sweden","highways", 
                      path=tempdir()) %>% 
  st_as_sf(.) %>% # as sf object 
  st_crop(., xmin = 17.55, xmax= 17.79, 
          ymin=59.9, ymax=59.8)

ggplot() +
  geom_sf(data = swe, 
          aes(geometry = swe$geometry), 
          fill= "antiquewhite")+
  geom_sf(data = roads, 
          aes(geometry = roads$geometry), 
          fill= "darkgrey")

# ggsave("uppsala_roads.png", width = 8, height = 6, dpi = 400)
```

```{r echo = FALSE}

library(mapview) 
roads %>% 
  mapview()
```

#### RAST VECT

```{r echo = FALSE}
library(raster) 
library(geodata) 
library(dplyr)

# elevation -------

swe <- gadm("Sweden", level=1, path=tempdir())%>% 
  crop(., extent(14, 25, 62, 69)) 
swe_3006 <- terra::project(swe, "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs")

plot(swe_3006) 

# png("vector.png", width = 24, height = 13.5, units = "cm", res = 400)
plot(swe_3006, col=over.col(100)) 
# dev.off()

dem.c1 <- geodata::elevation_30s(country="SWE", path=tempdir()) %>% 
  crop(., extent(14, 25, 62, 69))

dem.c1 <- terra::project(dem.c1, "+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs")

plot(dem.c1)

over.col <- colorRampPalette(c("white", "black"))

# save rast map----

# png("raster.png", width = 24, height = 13.5, units = "cm", res = 400)
plot(dem.c1, col=over.col(100)) 
# dev.off()

# save rast map ----

# png("raster_col.png", width = 24, height = 13.5, units = "cm", res = 400)

plot(dem.c1) 
# dev.off()

# str(dem.c1$SWE_elv_msk)


```
